In [3]:
print("hello")

hello

In [7]:
df = pd.read_csv("Used_Bikes (1).csv")

In [8]:
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [9]:
import pandas as pd

# Load CSV file
df = pd.read_csv("Used_Bikes (1).csv")

# Display data
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [10]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\harru\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (2.4.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.0-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 424.5 kB/s eta 0:00:18
   -- ------------------------------------- 0.5/8.1 MB 424.5 kB/s eta 0:00:18
   -- ------------------------------------- 0.5/8.1 MB 424.5 kB/s eta 0:00:18
   --- ------------------------------------ 0.8/8.1 MB 453.5 kB/s eta 0:00:17
   --- ------------------------------------ 0.8/8.1 MB 453.5 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/8.1 MB 461.8 kB/s eta 0:00:16
   ----- ---------------------------------- 1.0/8.1 MB 461.8 kB/s eta 0:00:16
   ----- ---------------------------------- 1.0/8.1 MB 461.8 kB/s eta 0:00:16
   ------ --------------------------------- 1.3/8.1 MB 472.5 kB/s eta 0:00:15
   ------ --------------------------------- 1.3/8.1 MB 472.5 kB/s eta 0:00:15
   ------ --------------------------------- 1.3/8.1 MB 472.5 kB/s eta 0:00:15
   ------- -------------------------------- 1.6/8.1 MB 451.8 kB/s eta 0:00:15
   ------- -------------------------------- 1.6/8.1 MB 451.8 kB/s eta 0:00:15
   ------- -------------------------------- 1.6/8.1 MB 451.8 kB/s eta 0:00:15
   --------- ------------------------------ 1.8/8.1 MB 448.1 kB/s eta 0:00:14
   --------- ------------------------------ 1.8/8.1 MB 448.1 kB/s eta 0:00:14
   --------- ------------------------------ 1.8/8.1 MB 448.1 kB/s eta 0:00:14
   --------- ------------------------------ 1.8/8.1 MB 448.1 kB/s eta 0:00:14
   --------- ------------------------------ 1.8/8.1 MB 448.1 kB/s eta 0:00:14
   --------- ------------------------------ 1.8/8.1 MB 448.1 kB/s eta 0:00:14
   ---------- ----------------------------- 2.1/8.1 MB 379.0 kB/s eta 0:00:16
   ---------- ----------------------------- 2.1/8.1 MB 379.0 kB/s eta 0:00:16
   ---------- ----------------------------- 2.1/8.1 MB 379.0 kB/s eta 0:00:16
   ---------- ----------------------------- 2.1/8.1 MB 379.0 kB/s eta 0:00:16
   ---------- ----------------------------- 2.1/8.1 MB 379.0 kB/s eta 0:00:16
   ---------- ----------------------------- 2.1/8.1 MB 379.0 kB/s eta 0:00:16
   ---------- ----------------------------- 2.1/8.1 MB 379.0 kB/s eta 0:00:16
   ---------- ----------------------------- 2.1/8.1 MB 379.0 kB/s eta 0:00:16
   ---------- ----------------------------- 2.1/8.1 MB 379.0 kB/s eta 0:00:16
   ----------- ---------------------------- 2.4/8.1 MB 305.4 kB/s eta 0:00:19
   ----------- ---------------------------- 2.4/8.1 MB 305.4 kB/s eta 0:00:19
   ----------- ---------------------------- 2.4/8.1 MB 305.4 kB/s eta 0:00:19
   ----------- ---------------------------- 2.4/8.1 MB 305.4 kB/s eta 0:00:19
   ----------- ---------------------------- 2.4/8.1 MB 305.4 kB/s eta 0:00:19
   ------------ --------------------------- 2.6/8.1 MB 302.3 kB/s eta 0:00:19
   ------------ --------------------------- 2.6/8.1 MB 302.3 kB/s eta 0:00:19
   ------------ --------------------------- 2.6/8.1 MB 302.3 kB/s eta 0:00:19
   ------------ --------------------------- 2.6/8.1 MB 302.3 kB/s eta 0:00:19
   ------------ --------------------------- 2.6/8.1 MB 302.3 kB/s eta 0:00:19
   -------------- ------------------------- 2.9/8.1 MB 297.6 kB/s eta 0:00:18
   -------------- ------------------------- 2.9/8.1 MB 297.6 kB/s eta 0:00:18
   -------------- ------------------------- 2.9/8.1 MB 297.6 kB/s eta 0:00:18
   -------------- ------------------------- 2.9/8.1 MB 297.6 kB/s eta 0:00:18
   -------------- ------------------------- 2.9/8.1 MB 297.6 kB/s eta 0:00:18
   --------------- ------------------------ 3.1/8.1 MB 289.2 kB/s eta 0:00:18
   --------------- ------------------------ 3.1/8.1 MB 289.2 kB/s eta 0:00:18
   --------------- ------------------------ 3.1/8.1 MB 289.2 kB/s eta 0:00:18
   --------------- ------------------------ 3.1/8.1 MB 289.2 kB/s eta 0:00:18
   ---------------- ----------------------- 3.4/8.1 MB 295.4 kB/s eta 0:00:16
   ---------------- ----------------------- 3.4/8.1 MB 295.4 kB/s eta 0:00:16
   ------------------ --------------------- 3.7/8.1 MB 303.4 kB/s eta 0:00:15
   ------------------ --------------------- 3.7/8.1 MB 303.4 kB/s eta 0:00:15
   ------------------ --------------------- 3.7/8.1 MB 303.4 kB/s eta 0:00:15
   ------------------ --------------------- 3.7/8.1 MB 303.4 kB/s eta 0:00:15
   ------------------- -------------------- 3.9/8.1 MB 304.4 kB/s eta 0:00:14
   ------------------- -------------------- 3.9/8.1 MB 304.4 kB/s eta 0:00:14
   ------------------- -------------------- 3.9/8.1 MB 304.4 kB/s eta 0:00:14
   ------------------- -------------------- 3.9/8.1 MB 304.4 kB/s eta 0:00:14
   ------------------- -------------------- 3.9/8.1 MB 304.4 kB/s eta 0:00:14
   -------------------- ------------------- 4.2/8.1 MB 303.2 kB/s eta 0:00:13
   -------------------- ------------------- 4.2/8.1 MB 303.2 kB/s eta 0:00:13
   ---------------------- ----------------- 4.5/8.1 MB 309.7 kB/s eta 0:00:12
   ---------------------- ----------------- 4.5/8.1 MB 309.7 kB/s eta 0:00:12
   ---------------------- ----------------- 4.5/8.1 MB 309.7 kB/s eta 0:00:12
   ---------------------- ----------------- 4.5/8.1 MB 309.7 kB/s eta 0:00:12
   ----------------------- ---------------- 4.7/8.1 MB 309.5 kB/s eta 0:00:11
   ----------------------- ---------------- 4.7/8.1 MB 309.5 kB/s eta 0:00:11
   ----------------------- ---------------- 4.7/8.1 MB 309.5 kB/s eta 0:00:11
   ----------------------- ---------------- 4.7/8.1 MB 309.5 kB/s eta 0:00:11
   ----------------------- ---------------- 4.7/8.1 MB 309.5 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.0/8.1 MB 305.1 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.1 MB 281.3 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.1 MB 281.3 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.1 MB 281.3 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.1 MB 281.3 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.1 MB 281.3 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.1 MB 281.3 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.1 MB 281.3 kB/s eta 0:00:11
   ------------------------- -------------- 5.2/8.1 MB 281.3 kB/s eta 0:00:11
   --------------------------- ------------ 5.5/8.1 MB 271.4 kB/s eta 0:00:10
   --------------------------- ------------ 5.5/8.1 MB 271.4 kB/s eta 0:00:10
   --------------------------- ------------ 5.5/8.1 MB 271.4 kB/s eta 0:00:10
   --------------------------- ------------ 5.5/8.1 MB 271.4 kB/s eta 0:00:10
   --------------------------- ------------ 5.5/8.1 MB 271.4 kB/s eta 0:00:10
   --------------------------- ------------ 5.5/8.1 MB 271.4 kB/s eta 0:00:10
   ---------------------------- ----------- 5.8/8.1 MB 265.7 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.1 MB 265.7 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.1 MB 265.7 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.1 MB 265.7 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.1 MB 265.7 kB/s eta 0:00:09
   ---------------------------- ----------- 5.8/8.1 MB 265.7 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.1 MB 263.4 kB/s eta 0:00:08
   ----------------------------- ---------- 6.0/8.1 MB 263.4 kB/s eta 0:00:08
   ----------------------------- ---------- 6.0/8.1 MB 263.4 kB/s eta 0:00:08
   ----------------------------- ---------- 6.0/8.1 MB 263.4 kB/s eta 0:00:08
   ----------------------------- ---------- 6.0/8.1 MB 263.4 kB/s eta 0:00:08
   ----------------------------- ---------- 6.0/8.1 MB 263.4 kB/s eta 0:00:08
   ------------------------------- -------- 6.3/8.1 MB 258.1 kB/s eta 0:00:07
   ------------------------------- -------- 6.3/8.1 MB 258.1 kB/s eta 0:00:07
   ------------------------------- -------- 6.3/8.1 MB 258.1 kB/s eta 0:00:07
   ------------------------------- -------- 6.3/8.1 MB 258.1 kB/s eta 0:00:07
   ------------------------------- -------- 6.3/8.1 MB 258.1 kB/s eta 0:00:07
   ------------------------------- -------- 6.3/8.1 MB 258.1 kB/s eta 0:00:07
   ------------------------------- -------- 6.3/8.1 MB 258.1 kB/s eta 0:00:07
   -------------------------------- ------- 6.6/8.1 MB 253.3 kB/s eta 0:00:07
   -------------------------------- ------- 6.6/8.1 MB 253.3 kB/s eta 0:00:07
   -------------------------------- ------- 6.6/8.1 MB 253.3 kB/s eta 0:00:07
   -------------------------------- ------- 6.6/8.1 MB 253.3 kB/s eta 0:00:07
   --------------------------------- ------ 6.8/8.1 MB 255.0 kB/s eta 0:00:06
   --------------------------------- ------ 6.8/8.1 MB 255.0 kB/s eta 0:00:06
   --------------------------------- ------ 6.8/8.1 MB 255.0 kB/s eta 0:00:06
   --------------------------------- ------ 6.8/8.1 MB 255.0 kB/s eta 0:00:06
   ---------------------------------- ----- 7.1/8.1 MB 257.5 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.1 MB 257.5 kB/s eta 0:00:04
   ---------------------------------- ----- 7.1/8.1 MB 257.5 kB/s eta 0:00:04
   ------------------------------------ --- 7.3/8.1 MB 260.5 kB/s eta 0:00:03
   ------------------------------------ --- 7.3/8.1 MB 260.5 kB/s eta 0:00:03
   ------------------------------------ --- 7.3/8.1 MB 260.5 kB/s eta 0:00:03
   ------------------------------------ --- 7.3/8.1 MB 260.5 kB/s eta 0:00:03
   ------------------------------------ --- 7.3/8.1 MB 260.5 kB/s eta 0:00:03
   ------------------------------------ --- 7.3/8.1 MB 260.5 kB/s eta 0:00:03
   ------------------------------------ --- 7.3/8.1 MB 260.5 kB/s eta 0:00:03
   ------------------------------------- -- 7.6/8.1 MB 257.3 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.1 MB 257.3 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.1 MB 257.3 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.1 MB 257.3 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.1 MB 257.3 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.1 MB 257.3 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.1 MB 257.3 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.1 MB 257.3 kB/s eta 0:00:02
   -------------------------------------- - 7.9/8.1 MB 247.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 247.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 247.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 247.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 247.0 kB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 247.0 kB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 236.6 kB/s  0:00:32
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.0-cp314-cp314-win_amd64.whl (37.1 MB)
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.1 MB ? eta -:--:--
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.5/37.1 MB 63.8 kB/s eta 0:09:33
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
    --------------------------------------- 0.8/37.1 MB 70.6 kB/s eta 0:08:34
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.0/37.1 MB 78.7 kB/s eta 0:07:38
   - -------------------------------------- 1.3/37.1 MB 73.4 kB/s eta 0:08:08
   - -------------------------------------- 1.3/37.1 MB 73.4 kB/s eta 0:08:08
   - -------------------------------------- 1.3/37.1 MB 73.4 kB/s eta 0:08:08
   - -------------------------------------- 1.3/37.1 MB 73.4 kB/s eta 0:08:08
   - -------------------------------------- 1.3/37.1 MB 73.4 kB/s eta 0:08:08
   - -------------------------------------- 1.3/37.1 MB 73.4 kB/s eta 0:08:08
   - -------------------------------------- 1.3/37.1 MB 73.4 kB/s eta 0:08:08
   - -------------------------------------- 1.3/37.1 MB 73.4 kB/s eta 0:08:08

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import sklearn as sns

In [15]:
# 1. Define your features (everything except price)
x = df.drop('price', axis=1) 

# 2. Define your target (only the price column)
y = df['price']

# 3. Now you can run the split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [16]:
print(x_train.shape)
print(x_test.shape)     
print(y_train.shape)
print(y_test.shape)

(26118, 7)
(6530, 7)
(26118,)
(6530,)

In [17]:
x_test

,bike_name,city,kms_driven,owner,age,power,brand
28994,Hero CD Deluxe 100cc,Chennai,22824.0,First Owner,8.0,100.0,Hero
31433,Honda CB Trigger 150cc,Bangalore,42837.0,First Owner,8.0,150.0,Honda
17250,Bajaj Pulsar 150cc,Ghaziabad,64955.0,First Owner,15.0,150.0,Bajaj
13738,Bajaj Pulsar 150cc,Bhopal,36000.0,First Owner,15.0,150.0,Bajaj
24577,Royal Enfield Classic 350cc,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...
21858,Yamaha SZ-RR 150cc,Kanchipuram,52000.0,First Owner,10.0,150.0,Yamaha
11813,Hero Hunk Rear Disc 150cc,Delhi,48587.0,First Owner,8.0,150.0,Hero
7033,Harley-Davidson Iron 883,Delhi,20000.0,Second Owner,4.0,883.0,Harley-Davidson
7406,Bajaj Avenger Street 150,Delhi,25400.0,First Owner,5.0,150.0,Bajaj
31555,Bajaj Avenger Street 220,Mumbai,8000.0,First Owner,5.0,220.0,Bajaj

In [18]:
y_train

17390     80000.0
19014     25000.0
16949     39000.0
25968     25000.0
380       42000.0
           ...
29802    105000.0
5390      48000.0
860       45000.0
15795     23000.0
23654     41000.0
Name: price, Length: 26118, dtype: float64

In [19]:
x_test

,bike_name,city,kms_driven,owner,age,power,brand
28994,Hero CD Deluxe 100cc,Chennai,22824.0,First Owner,8.0,100.0,Hero
31433,Honda CB Trigger 150cc,Bangalore,42837.0,First Owner,8.0,150.0,Honda
17250,Bajaj Pulsar 150cc,Ghaziabad,64955.0,First Owner,15.0,150.0,Bajaj
13738,Bajaj Pulsar 150cc,Bhopal,36000.0,First Owner,15.0,150.0,Bajaj
24577,Royal Enfield Classic 350cc,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...
21858,Yamaha SZ-RR 150cc,Kanchipuram,52000.0,First Owner,10.0,150.0,Yamaha
11813,Hero Hunk Rear Disc 150cc,Delhi,48587.0,First Owner,8.0,150.0,Hero
7033,Harley-Davidson Iron 883,Delhi,20000.0,Second Owner,4.0,883.0,Harley-Davidson
7406,Bajaj Avenger Street 150,Delhi,25400.0,First Owner,5.0,150.0,Bajaj
31555,Bajaj Avenger Street 220,Mumbai,8000.0,First Owner,5.0,220.0,Bajaj

In [20]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [26]:
# 1. Sirf numerical columns (price, age, kms, power) rakhein
df_numeric = df.select_dtypes(include=['number'])

# 2. X (Features) aur y (Target) define karein
X = df_numeric.drop('price', axis=1) # price hata kar sab features hain
y = df_numeric['price']              # price target hai

# 3. Data split karein
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Model train karein
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

print("Training Done! Ab aap prediction kar sakte hain.")

Training Done! Ab aap prediction kar sakte hain.

In [27]:
print("Model Score:", lr.score(X_test, y_test))

Model Score: 0.7316121931380841

In [28]:
df.head

<bound method NDFrame.head of                                   bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0
2                      Triumph Daytona 675R  600000.0      Delhi       110.0
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0
...                                     ...       ...        ...         ...
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0

             owner   age  power          brand
0      First Owner   3.0  110.0            TVS
1      First Owner   4.0  350.0  Royal Enfield
2      First Owner   8.0  675.0        Triumph
3      First Owner   4.0  180.0            TVS
4      First Owner   3.0  150.0         Yamaha
...            ...   ...    ...            ...
32643  First Owner   4.0  100.0           Hero
32644  First Owner   9.0  180.0            TVS
32645  First Owner   6.0  220.0          Bajaj
32646  First Owner  16.0  125.0           Hero
32647  First Owner  13.0  150.0          Bajaj

[32648 rows x 8 columns]>

In [30]:
honda_bike=[[15000,2015,15000,1]]
df.head

<bound method NDFrame.head of                                   bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0
2                      Triumph Daytona 675R  600000.0      Delhi       110.0
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0
...                                     ...       ...        ...         ...
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0

             owner   age  power          brand
0      First Owner   3.0  110.0            TVS
1      First Owner   4.0  350.0  Royal Enfield
2      First Owner   8.0  675.0        Triumph
3      First Owner   4.0  180.0            TVS
4      First Owner   3.0  150.0         Yamaha
...            ...   ...    ...            ...
32643  First Owner   4.0  100.0           Hero
32644  First Owner   9.0  180.0            TVS
32645  First Owner   6.0  220.0          Bajaj
32646  First Owner  16.0  125.0           Hero
32647  First Owner  13.0  150.0          Bajaj

[32648 rows x 8 columns]>

In [31]:
import pandas as pd
df = pd.read_csv("Used_Bikes (1).csv")

In [33]:
df = df.drop_duplicates()
print("Duplicates removed!")

Duplicates removed!

In [34]:
import pandas as pd
df = pd.read_csv("Used_Bikes (1).csv")

In [35]:

df = df.dropna()

In [36]:

df = pd.get_dummies(df, columns=['brand', 'city'], drop_first=True)

In [38]:
df.head

<bound method NDFrame.head of                                   bike_name     price  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0     17654.0
1               Royal Enfield Classic 350cc  119900.0     11000.0
2                      Triumph Daytona 675R  600000.0       110.0
3                      TVS Apache RTR 180cc   65000.0     16329.0
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0     10000.0
...                                     ...       ...         ...
32643                Hero Passion Pro 100cc   39000.0     22000.0
32644                  TVS Apache RTR 180cc   30000.0      6639.0
32645              Bajaj Avenger Street 220   60000.0     20373.0
32646             Hero Super Splendor 125cc   15600.0     84186.0
32647                    Bajaj Pulsar 150cc   22000.0     60857.0

             owner   age  power  brand_Bajaj  brand_Benelli  brand_Ducati  \
0      First Owner   3.0  110.0        False          False         False
1      First Owner   4.0  350.0        False          False         False
2      First Owner   8.0  675.0        False          False         False
3      First Owner   4.0  180.0        False          False         False
4      First Owner   3.0  150.0        False          False         False
...            ...   ...    ...          ...            ...           ...
32643  First Owner   4.0  100.0        False          False         False
32644  First Owner   9.0  180.0        False          False         False
32645  First Owner   6.0  220.0         True          False         False
32646  First Owner  16.0  125.0        False          False         False
32647  First Owner  13.0  150.0         True          False         False

       brand_Harley-Davidson  ...  city_Viramgam  city_Virar  \
0                      False  ...          False       False
1                      False  ...          False       False
2                      False  ...          False       False
3                      False  ...          False       False
4                      False  ...          False       False
...                      ...  ...            ...         ...
32643                  False  ...          False       False
32644                  False  ...          False       False
32645                  False  ...          False       False
32646                  False  ...          False       False
32647                  False  ...          False       False

       city_Virudhunagar  city_Visakhapatnam  city_Vizianagaram  \
0                  False               False              False
1                  False               False              False
2                  False               False              False
3                  False               False              False
4                  False               False              False
...                  ...                 ...                ...
32643              False               False              False
32644              False               False              False
32645              False               False              False
32646              False               False              False
32647              False               False              False

       city_Warangal  city_Wardha  city_Yamuna Nagar  city_Yemmiganur  \
0              False        False              False            False
1              False        False              False            False
2              False        False              False            False
3              False        False              False            False
4              False        False              False            False
...              ...          ...                ...              ...
32643          False        False              False            False
32644          False        False              False            False
32645          False        False              False            False
32646          False        False              False            False
32647          False        False              False            False

       city_Zirakpur
0              False
1              False
2              False
3              False
4              False
...              ...
32643          False
32644          False
32645          False
32646          False
32647          False

[32648 rows x 470 columns]>